name: Automated Workflow | Tech Challenge - FIAP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest
    
    env:
      Solution_Name: TCFiapProducerDeleteContact.sln
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }} 


    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Instalar .NET 8
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restaurar e compilar
      - name: Restore and build the application
        run: |
          dotnet restore ${{ env.Solution_Name }}
          dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

      # Fazer login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest

      # Enviar a imagem para o Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_IMAGENAME }}:${{ github.sha }}
          docker push ${{ secrets.DOCKER_IMAGENAME }}:latest
